---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: enum
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  strict: 0
resources:
  repository: git://github.com/neilbowers/enum.git
version: 1.04
